<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Project Properties">
    <OutputType>Exe</OutputType>
    <TargetFramework>$(FrameworkBase)</TargetFramework>
    <AutoreleasePoolSupport>true</AutoreleasePoolSupport>
    <UseCurrentRuntimeIdentifier>true</UseCurrentRuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup Label="NuGet Packages">
    <PackageReference Include="Eto.Platform.Mac64" Version="2.9.0" />
  </ItemGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\OpenTabletDriver.UX\OpenTabletDriver.UX.csproj" />
  </ItemGroup>

  <ItemGroup Label="Project Resources">
    <Content Include="../eng/macos/Icon.icns" />
    <None Include="../eng/macos/Info.plist" />
  </ItemGroup>

  <Target Name="RemoveRedundantDir" AfterTargets="MacCopyPublishFiles" Condition="$([MSBuild]::IsOsPlatform(OSX))">
    <RemoveDir Directories="$(LauncherPath)$(MacBundleName).app" />
  </Target>

  <Target Name="AdhocCodeSign" AfterTargets="RemoveRedundantDir;MacFinishBundle" Condition="$([MSBuild]::IsOsPlatform(OSX))">
    <Exec Command="codesign  -s - -f --deep &quot;$(OutputAppPath)&quot;" />
  </Target>

</Project>
